### PR TITLE
sys.argv does not exist in some environments where the Python interpreter is embedded.

### PR DESCRIPTION
**Pull request by aren**

### CODE REVIEW

**Comment by aren** [comment]
@coryvirok, this implements your feedback from PR #130. If it needs something else before you can merge, please let me know.

**Comment by ezarowny** [comment]
This is pretty interesting. Which environment are you testing on?

**Comment by aren** [comment]
I think this is an issue anywhere the python interpreter is embedded (https://docs.python.org/3/extending/embedding.html). In our case, it's this extension to FreeRADIUS (https://github.com/FreeRADIUS/freeradius-server/blob/v4.0.x/src/modules/rlm_python/rlm_python.c).

**Comment by brianr** [comment]
Thanks @aren!

**Comment by ezarowny** [comment]
@aren I'll cut a release of pyrollbar containing this change sometime this afternoon. Thanks for your pull request!

**Pull request merged**
