### PR TITLE
Add additional hooks on django middleware

### PR DESCRIPTION
**Pull request by filwaitman**
Child of https://github.com/rollbar/pyrollbar/pull/137 (see this for the entire thread)

### CODE REVIEW

**Comment by ezarowny** [comment]
Ah, I see what you might want to do here. I'm going to discuss this with another engineer. Could be useful!

**Comment by ezarowny** [comment]
Hey there, just wanted to say that we haven't forgotten about you. We want to support this feature and we're trying to decide the best way to go about it.

**Comment by filwaitman** [comment]
hahaha

ok @ezarowny, no rush!  =]

**Comment by ezarowny** [comment]
Hey @filwaitman, sorry for the delay there.

The middleware solution here is definitely a valid way to go about this but I've been trying to think of a way that would feel more official. As far as I know, you can't pass any arguments to the `__init__(...)` function of a Django Middleware.

As Django's settings files are just Python files, what do you think about storing or importing the `get_payload_data` and `get_extra_data` functions into your Django settings file? We could then look at them when initializing the Middleware?

**Comment by filwaitman** [comment]
Hi!

Sounds a good idea.
I can't work on it now, though. I guess next month I can do that.

**Comment by ezarowny** [comment]
Oh that's alright. I'll get a PR together with how I think this should work and I'll tag you so we can discuss it.

**Comment by filwaitman** [comment]
Ok, sounds perfect!

**Comment by coryvirok** [comment]
@ezarowny what's next for this PR?

**Comment by ezarowny** [comment]
Just need to write up the handlers for Django and test it out.

**Comment by GabLeRoux** [comment]
I'm interested in this as well, any progress or plan to support this? I'm looking for a way to specify which user had the problem with some stacktrace and this seems like a potential solution.

**Pull request merged**
