### PR TITLE
Update Readme with correct Travis build status link

### PR DESCRIPTION
**Pull request by mrunalk**
Using the latest link as described here, https://docs.travis-ci.com/user/status-images/#travis-ci-pages-show-the-default-branchs-result

### CODE REVIEW

**Comment by mrunalk** [comment]
Thanks for catching this. I couldn't find any other reference to travis build in pyrollbar like the one you mentioned in rollbar.js.

**Comment by waltjones** [comment]
@mrunalk You're right. I think that's why the version in the badge is stuck at 0.14.2 while the latest release tag is at 0.15.0. 

Looks like it has to be updated manually, but the release process doc doesn't mention it.

**Comment by waltjones** [comment]
Maybe update the version to 0.15.0 in this PR?

**Comment by mrunalk** [comment]
Thanks @waltjones !

**Pull request merged**
