### PR TITLE
Add support for Falcon framework requests

### PR DESCRIPTION
**Pull request by rhcarvalho**

### CODE REVIEW

**Comment by brianr** [comment]
Thanks @rhcarvalho! Sorry it's taken so long to respond here, this one got a little lost...

Assuming you still want this, could you rebase it against master, and add a test? We'll be happy to merge it with a test.

**Comment by rhcarvalho** [comment]
Hi @brianr sorry for the delay. I'm not needing this anymore. Closing the PR. Thanks.

**Comment by brianr** [comment]
OK - no problem, thanks for clearing it out!

**Comment by rorytrent** [comment]
Hi, we are currently using rollbar with falcon in production and were wondering if this PR could be looked at again. We would greatly appreciate the additional request info from falcon without having to wrap the request or fork the library.

**Comment by rhcarvalho** [comment]
I'll update the PR.

**Comment by rokob** [comment]
LGTM

**Pull request merged**
