### PR TITLE
Update frameworks example apps

### PR DESCRIPTION
**Pull request by bxsx**
## Description of the change

Update Flask example to make it simpler and working.
Add note about required packages to the Twisted example

## Type of change
- [x] Bug fix (non-breaking change that fixes an issue)
- [x] Chore (non-breaking change)

## Related issues

> Fix ch79857

### CODE REVIEW

**Comment by bxsx** [comment]
I added f6547a6 to keep Django compatible across different versions.
It doesn't look great and contain redundant code due to Django's restrictions.

Another option would be to keep 2 examples version-dependent. Thoughts?

**Comment by waltjones** [comment]
Maybe clean up some of the duplication by setting up the keyword arguments first as a dict. You still have to call`settings.configure` conditionally, but the arguments are set up once (replacing/renaming the one argument of course).

**Comment by bxsx** [comment]
> Maybe clean up some of the duplication by setting up the keyword arguments first as a dict. You still have to call`settings.configure` conditionally, but the arguments are set up once (replacing/renaming the one argument of course).

Thank @waltjones ! I have added it at 7033c15

**Review by waltjones — APPROVED** [review]
:+1: Looks good.

**Review by pawelsz-rb — APPROVED** [review]

**Pull request merged**
