### PR TITLE
Handle disallowed host when getting uri

### PR DESCRIPTION
**Pull request by rgs258**
When request.build_absolute_uri() throws DisallowedHost then the message does not make it to Rollbar. This change catches the DisallowedHost exception and then calls request.get_raw_uri() to ensure that the message continues to process and become sent to Rollbar

### CODE REVIEW

**Comment by jessewgibbs** [comment]
@rgs258 thanks for submitting this.

@rokob can you take a look when you get a chance?

**Comment by rokob** [comment]
👍 Looks good to me

**Comment by ezarowny** [comment]
Why not use `get_raw_uri` all the time? `build_absolute_uri` is a more expensive call and from the perspective of an error I don't think it would matter. Maybe I'm missing something here?

**Comment by rokob** [comment]
Actually that is a good point, `build_absolute_uri` with a `None` location, basically boils down to the same thing as `get_raw_uri` plus a little bit of logic to maybe through the `DisallowedHost` exception. If we are just going to truck right through that then we should skip the ceremony and use `get_raw_uri` from the get-go. The only difference is that `get_raw_uri` returns a string and `build_absolute_uri` calls `iri_to_uri` on the string before returning. That extra call I don't think actually matters for our use case as we should theoretically accept full UTF-8 URLs even if that isn't what browsers work with.

**Pull request merged**
