### PR TITLE
Use formatted message for rollbar exceptions

### PR DESCRIPTION
**Pull request by srikiraju**

### CODE REVIEW

**Comment by brianr** [comment]
👍 I agree with this change.

@coryvirok or @ezarowny mind doing a code review?

**Comment by ezarowny** [comment]
Sure, I'll take a look at this today. For reference, this is related to #125.

**Comment by ezarowny** [comment]
Hey, we've looked into this and I think we're already doing the right thing.

Can you show me some sample code that generates an unformatted exception message?

**Comment by srikiraju** [comment]
If you log using:
```
log.exception("My formatted message: %s and %s", "foo", "bar")
```
The payload will generated with "My formatted message: %s and %s" instead of the expected "My formatted message: foo and bar"

**Comment by rokob** [comment]
This has been sitting here for a while, it looks good to me, I'm going to merge this unless someone has an issue.

**Comment by brianr** [comment]
Hrm - this is going to make grouping work differently (and probably, usually worse, though I suppose not always worse).

@srikiraju Can you tell us about your motivation here? Is it so that messages will be grouped separately based on the values of those parameters? Or are you more interested in the way they are displayed in the Rollbar UI?

**Comment by srikiraju** [comment]
@brianr This change will not change grouping behaviour. 

It will only change how the UI displays some exception type rollbar events.

**Comment by brianr** [comment]
@srikiraju Thanks for the reply; good to know the focus is on the UI.

The backend groups messages based on the text of the message. So, interpolating the values will cause those to be included in the grouping key, vs. not being included like they are now. That is going to cause them to be grouped separately, except for cases where the values are normalized (i.e. because they look like numbers or timestamps). More on this in [the docs](https://rollbar.com/docs/grouping-algorithm/#message-fingerprinting).

The UI part is totally fair and relevant though. I think we will need to address that in the Rollbar app, not in this SDK.

**Comment by srikiraju** [comment]
@brianr sorry if I wasn't clear. This changes *does not* change fingerprints on either Exception or Message type records. Exceptions do not get grouped based on the `description` - so their grouping doesn't change. Message events will retain the same behaviour after this change.

**Comment by srikiraju** [comment]
Ofcourse, it's totally possible to implement the exact same behaviour in the app as well by specifying a standard format across languages and interpolating them in that way.

**Comment by brianr** [comment]
Ohhh you are right. I misread the diff. I see it now.

Looks good to me 👍

**Pull request merged**
