### PR TITLE
Treq now requires bytes, not str, so encoding is up to the client

### PR DESCRIPTION
**Pull request by aren**
See https://github.com/twisted/treq/issues/151.

### CODE REVIEW

**Comment by jessewgibbs** [comment]
@aren thanks for the contribution. 

@rokob can you review?

**Comment by rokob** [comment]
My main concern is that this needs to work with both Python 2 and 3. I think we have tests for both and it looks like it is passing so it probably is okay. Let me just double check, but otherwise it looks good to me.

**Comment by aren** [comment]
I did test on both 2 and 3, but another set of eyes is always appreciated.

**Comment by AdrianLC** [comment]
:+1: I just tested this on python 3.6 seems to work. Really lucky I found the fix that you just sent today, thanks!

**Comment by rokob** [comment]
So I played around with this, `encode` can raise `UnicodeDecodeError` and `UnicodeEncodeError` depending on the value of the receiver, so I changed this to handle those exceptions, otherwise looks good to me.

**Pull request merged**
