### PR TITLE
fix json reporting for werkzeug and bottle

### LINKED ISSUE #82: JSON body causes Rollbar to reject submissions
Due to https://github.com/rollbar/pyrollbar/blob/ac8264cf90ef12bc46f704b97731ee6ff023fb03/rollbar/__init__.py#L1048, Rollbar rejects messages that have message bodies that are objects, not strings.

According to https://rollbar.com/docs/api/items_post/, the message should contain the raw POST body.

### PR DESCRIPTION
**Pull request by oyiptong**
fixes #82

### CODE REVIEW

**Comment by coryvirok** [comment]
Thanks for the PR. I'll take a look.

**Comment by oyiptong** [comment]
I haven't yet finished implementing it. I'm talking to rollbar support to see if the expectation was mismatched

**Comment by oyiptong** [comment]
essentially, the issue is that when I put a flask request in one of the reporting functions, rollbar seems to reject it, complaining that:

```json
{
  "message": "Invalid format. data.request.body object value found, but a string is required.", 
  "err": 1
}
```

**Comment by oyiptong** [comment]
the request has mime type application/json and the pyrollbar code serializes the body to json.

**Comment by coryvirok** [comment]
I see. I think what's happening here is that the new pyrollbar serializer is not forcing this into a string. The fix is to set `request_data['body'] = text(request.body)`

**Comment by oyiptong** [comment]
aha!

**Comment by oyiptong** [comment]
want to take care of it, or do you want me to add more commits and make the tests pass?

**Comment by coryvirok** [comment]
Please feel free to fix. Thanks!

**Comment by coryvirok** [comment]
I made a change on the server-side to accept the non-string payload related to this bug - https://github.com/rollbar/pyrollbar/issues/82

**Comment by oyiptong** [comment]
awesome! thank you

**Comment by oyiptong** [comment]
I will then close this bug

**Pull request closed without merging**
