### PR TITLE
Use callable() instead of try/except TypeError

### PR DESCRIPTION
**Pull request by denizdogan**
It seemed unnecessary to use try/except TypeError when checking if a value is callable, let me know what you think!

### CODE REVIEW

**Comment by denizdogan** [comment]
As far as I can tell, the CI failures are unrelated to the changes I made.

**Comment by waltjones** [comment]
@denizdogan Try rebasing master. https://github.com/rollbar/pyrollbar/pull/328 should have fixed the Travis issues.

**Comment by denizdogan** [comment]
@waltjones It seems to fail with the message: "Unable to download 3.3 archive. The archive may not exist. Please consider a different version."

Just out of curiosity, how long is Rollbar planning on supporting Python 3.3? It reached end-of-life more than two years ago and will no longer receive security updates.

**Comment by denizdogan** [comment]
Oh, it seems to work now? Weird. :)

**Comment by waltjones** [comment]
@denizdogan Rollbar will usually continue support for EOL versions if it's feasible to do so, if it's recently EOL, and if there are still people using it. I thought about whether to drop 3.3 yet, but the updates needed to keep it in travis weren't a big deal.

Thank you for the PR and the rebase.

**Pull request merged**
