### PR TITLE
Add quart to contrib

### PR DESCRIPTION
**Pull request by flyinactor91**
This adds support for the Quart web framework to the Rollbar Python client.

Quart is an async web library that is feature-compatible with Flask and is usually a drop-in replacement. This makes converting Flask apps to Quart very easy. This also applies to making third-party extensions easy to integrate provided they already support Flask.

This pull request adds `rollbar.contrib.quart` which copies `rollbar.contrib.flask` with minor changes.

I've also created a gist showing an example Quart app based on the Flask example linked to in the Rollbar docs:
https://gist.github.com/flyinactor91/a6afb0a62d9ea69aa9ebecc2ff63bdbf

A note in the example app: line 35 adds `weak=False` to the `connect` call. If the default `True` is kept, the `blinker` Signal class will delete the Rollbar handler prematurely and signals won't reach Rollbar's servers.

### CODE REVIEW

**Comment by jessewgibbs** [comment]
@flyinactor91 thanks for the contribution.

@rokob can you review when you get a chance?

**Comment by rokob** [comment]
Will `if WerkzeugRequest and isinstance(request, WerkzeugRequest):` return true for the quart request object? This is what Flask uses so presumably if it is a drop-in replacement then yes, but just want to double check.

**Comment by flyinactor91** [comment]
My guess is no. Flask uses Werkzeug as its WSGI layer, but Quart uses Hypercorn as its ASGI layer. You can think of Hypercorn as an async version of Werkzeug, which allows Quart to be an async version of Flask. All of the imports are the same between the two libraries.

https://github.com/pgjones/hypercorn

For what it's worth, the code copied in the example app above has been working flawlessly  in production for the last month.

**Comment by rokob** [comment]
Working meaning that rollbar items have data from the request? If that is true then everything is cool. The only thing that could happen is that items would not have data pulled from the request.

**Comment by flyinactor91** [comment]
Rollbar has been pulling in the stack trace, exception, and function params into the UI, so everything works as far as I can tell.

**Pull request merged**
