### PR TITLE
Adds AppEngine support to pyrollbar module (fixes #42)

### LINKED ISSUE #42: Allow the use of Rollbar module on free Appengine apps
Hey. 

I have a free Appengine app (http://matrufsc2.appspot.com) and I'm having problems on using pyrollbar on production: Every time an exception is raised in the program,  Appengine show the following message in log:

```
Exception while posting item FeatureNotEnabledError('The Socket API will be enabled for this application once billing has been enabled in the admin console.',)
Traceback (most recent call last):
  File "/base/data/home/apps/s~matrufsc2/1.380938498181301988/gaenv_lib/rollbar/__init__.py", line 1025, in _send_payload
    _post_api('item/', payload, access_token=payload.get('access_token'))
  File "/base/data/home/apps/s~matrufsc2/1.380938498181301988/gaenv_lib/rollbar/__init__.py", line 1044, in _post_api
    verify=SETTINGS.get('verify_https', True))
  File "/base/data/home/apps/s~matrufsc2/1.380938498181301988/gaenv_lib/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/base/data/home/apps/s~matrufsc2/1.380938498181301988/gaenv_lib/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/base/data/home/apps/s~matrufsc2/1.380938498181301988/gaenv_lib/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/base/data/home/apps/s~matrufsc2/1.380938498181301988/gaenv_lib/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/base/data/home/apps/s~matrufsc2/1.380938498181301988/gaenv_lib/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/base/data/home/apps/s~matrufsc2/1.380938498181301988/gaenv_lib/requests/packages/urllib3/connectionpool.py", line 518, in urlopen
    body=body, headers=headers)
  File "/base/data/home/apps/s~matrufsc2/1.380938498181301988/gaenv_lib/requests/packages/urllib3/connectionpool.py", line 322, in _make_request
    self._validate_conn(conn)
  File "/base/data/home/apps/s~matrufsc2/1.380938498181301988/gaenv_lib/requests/packages/urllib3/connectionpool.py", line 727, in _validate_conn
    conn.connect()
  File "/base/data/home/apps/s~matrufsc2/1.380938498181301988/gaenv_lib/requests/packages/urllib3/connection.py", line 204, in connect
    conn = self._new_conn()
  File "/base/data/home/apps/s~matrufsc2/1.380938498181301988/gaenv_lib/requests/packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/base/data/home/apps/s~matrufsc2/1.380938498181301988/gaenv_lib/requests/packages/urllib3/util/connection.py", line 64, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/remote_socket/_remote_socket.py", line 339, in getaddrinfo
    canonical=(flags & AI_CANONNAME))
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/remote_socket/_remote_socket.py", line 212, in _Resolve
    canon, aliases, addresses = _ResolveName(name, families)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/remote_socket/_remote_socket.py", line 230, in _ResolveName
    apiproxy_stub_map.MakeSyncCall('remote_socket', 'Resolve', request, reply)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 95, in MakeSyncCall
    return stubmap.MakeSyncCall(service, call, request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 329, in MakeSyncCall
    rpc.CheckSuccess()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_rpc.py", line 134, in CheckSuccess
    raise self.exception
FeatureNotEnabledError: The Socket API will be enabled for this application once billing has been enabled in the admin console.
```
As you can see, all the traceback starts with the call made by pyrollbar to requests, which uses urllib3 which uses socket API to get addr info about rollbar host and other things of that type.

Maybe this should be reported as an issue of urllib3, but, as i'm not using urllib3 at all in my code, in my case just pyrollbar is causing that problem. 

That's it. 

Thanks.

### PR DESCRIPTION
**Pull request by fjorgemota**
Please, check that change with the maximum attention. I feel much like the code is a bit duplicated (just some lines have been modified), but that's all for using pyrollbar with AppEngine. (checked as working in dev_appserver.py of AppEngine's SDK)

And it fixes issue #42, too. =)

Thanks. =)

### CODE REVIEW

**Comment by brianr** [comment]
Thanks for the PR, @fjorgemota ! We'll get this reviewed and merged shortly.

**Comment by fjorgemota** [comment]
Awesome, thanks @brianr. I'll await a review. =)

**Comment by coryvirok** [comment]
I've verified that this works in my dev environment although I had to go through some crazy hoops to get it working with App Engine, (http://stackoverflow.com/questions/16192916/importerror-no-module-named-ssl-with-dev-appserver-py-from-google-app-engine/16937668#16937668)

Thanks for the PR!

**Comment by fjorgemota** [comment]
Awesome, thanks, @coryvirok! :D

**Comment by ekampf** [comment]
@fjorgemota @coryvirok if you're on AppEngine, you probably are not using (and don't have) the 'requests' library...  which means you'll fail on __init__.py "import requests" no?

**Comment by fjorgemota** [comment]
@ekampf Hey, i'm using this module in production at matrufsc2.appspot.com (the repository is here: http://github.com/matrufsc2/matrufsc2) and it seems to work correctly, even with that line on __init__.py file.

Are you suffering from a related caused by that line?

Thanks.

**Comment by ekampf** [comment]
@fjorgemota yes. my code throws on that line (and if I comment it out on it crashes on line #1177:
```
if isinstance(resp, requests.Response):
```
in _parse_response

How come your code successfully imports requests?  its not part of the default app engine stack...

**Comment by fjorgemota** [comment]
@ekampf As I remember, seems like you can INSTALL requests normally (in my case, I installed it using gaenv, which allow the use of any library in Pypi easily in AppEngine), but you CANNOT use requests to make requests.

Because this my project can import requests, but uses the GAE support added in this pull request to send exception from AppEngine's Python environment to Rollbar using URLFetch. =)

**Comment by ekampf** [comment]
@fjorgemota got it!
Still would be nice if you wouldn't have to install requests at all (as its not being used)

**Pull request merged**
