### PR TITLE
fix #373 breaking collecting user information on *not* starlette

### PR DESCRIPTION
**Pull request by terencehonles**
## Description of the change

The change fixes the check to match the previous code:

  `if not StarletteRequest and hasattr(request, 'user'):`

## Type of change
- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues
 
- fix [ch91323]

### Development

- [x] Lint rules pass locally
- [x] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [x]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [x] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [x] Changes have been reviewed by at least one other engineer
- [x] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Comment by terencehonles** [comment]
@bxsx do you mind looking at this? This fixes the change here https://github.com/rollbar/pyrollbar/commit/0c59ade504c7b0ab339375d0a160a1dc5aee26c3 as part of #373

**Comment by bxsx** [comment]
Thanks for reporting and PR. The fix looks reasonable. I will double-check it next week as the failing commit was necessary to bypass Starlette's security layer. I want to make sure it works fine in both cases.

**Comment by terencehonles** [comment]
> Thanks for reporting and PR. The fix looks reasonable. I will double-check it next week as the failing commit was necessary to bypass Starlette's security layer. I want to make sure it works fine in both cases.

Thanks, the starlette path should still be taken if it's installed so it should be good, but we're running off our fork for the time being so no rush and do whatever validation you think is necessary. I'm slightly surprised there isn't a test for this since I noticed you *did* add a test for the starlette path.

**Comment by terencehonles** [comment]
@bxsx / @waltjones any chance this can be reviewed / merged sometime soon?

**Comment by waltjones** [comment]
@bxsx will need to look.

**Comment by terencehonles** [comment]
@bxsx any chance you have some time soon to review this?

**Review by bxsx — APPROVED** [review]

**Comment by bxsx** [comment]
Hi @terencehonles

Thanks again for the PR and sorry that it took a bit longer than it should.

I approved the changes and added more tests around, so both Django and Starlette should be safe now ;)
I also refactored the code, eliminating the anonymous function for better traceback and representation.

As this PR contains changes from another unmerged branch (to fix CI builds) it will be merged after #389 approval (within few days).

**Comment by bxsx** [comment]
@terencehonles we have just released the `0.16.2` version which includes this PR. Thank you for your contribution!

**Pull request merged**
